### ISSUE TITLE
java.io.FileNotFoundException libsunec.so

### ISSUE THREAD

**Issue by chr15m** [retrogradeorbit/bootleg#1]
```
$ bootleg 
Exception in thread "main" java.io.FileNotFoundException: /home/crispin/.bootleg/libs/libsunec.so
	at com.oracle.svm.core.posix.PosixUtils.fileOpen(PosixUtils.java:235)
	at java.io.FileOutputStream.open(FileOutputStream.java:580)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at clojure.java.io$fn__11504.invokeStatic(io.clj:319)
	at clojure.java.io$fn__11504.invoke(io.clj:319)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at clojure.java.io$copy.invokeStatic(io.clj:406)
	at clojure.java.io$copy.doInvoke(io.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at bootleg.config$setup.invokeStatic(config.clj:21)
	at bootleg.config$setup.invoke(config.clj:13)
	at bootleg.config$init_BANG_.invokeStatic(config.clj:31)
	at bootleg.config$init_BANG_.invoke(config.clj:23)
	at bootleg.core$_main.invokeStatic(core.clj:52)
	at bootleg.core$_main.doInvoke(core.clj:49)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at bootleg.core.main(Unknown Source)
```

**Comment by retrogradeorbit** [comment]
Rereleased a new version. Please download and try again.

**Comment by chr15m** [comment]
Fixed. :+1:
