### ISSUE TITLE
File not found error could be friendlier

### ISSUE THREAD

**Issue by chr15m** [retrogradeorbit/bootleg#8]
Currently a big fat stack trace. :)

```
$ bootleg goober
Exception in thread "main" java.io.FileNotFoundException: goober
	at com.oracle.svm.core.posix.PosixUtils.fileOpen(PosixUtils.java:235)
	at java.io.FileInputStream.open(FileInputStream.java:481)
...
```

**Comment by retrogradeorbit** [comment]
There are presently no error messages of any kind. This is definitely an area that needs improvement.

**Comment by retrogradeorbit** [comment]
a1fa5e144bb9793c13352541a90142087f38927e
